-- (STORED PROCEDURES) PROCEDIMENTOS ARMAZENADOS
-- CRIA UM PROCEDURE
CREATE OR ALTER PROCEDURE [spListCourse] AS 
  SELECT * FROM [Curso]

EXEC [spListCourse]

-- DROPA(EXCLUI) UMA LISTA
  DROP PROCEDURE [spListCourse]