CREATE DATABASE [CSharp]
GO

SELECT NEWID() -- GERA UM WID E É COMPATÍVEL COM C#
SELECT GETDATE() -- PEGA DATA ATUAL DO SERVIDOR
SELECT GETUTCDATE() -- PEGA DATA COM FORMATO UTC

USE [CSharp]
GO

-- ESTRUTURA DA TABELA ALUNO
CREATE TABLE [Student]
(
  [Id]uniqueidentifier NOT NULL, -- (uniqueidentifier) USA MUITO MAIS ESPAÇO DO QUE (INT)
  [Name]NVARCHAR(120) NOT NULL,
  [Email]NVARCHAR(180) NOT NULL,
  [Document]NVARCHAR(20) NULL,
  [Phone]NVARCHAR(20) NULL,
  [BirthDate]DATETIME NULL,
  [CreateDate]DATETIME NOT NULL DEFAULT(GETDATE()),
  CONSTRAINT [PK_Student] PRIMARY KEY ([Id])
);
GO

-- ESTRUTURA DA TABELA AUTOR
CREATE TABLE [Author]
(
  [Id]uniqueidentifier NOT NULL,
  [Name]NVARCHAR(80) NOT NULL,
  [Title]NVARCHAR(80) NOT NULL,
  [Image]NVARCHAR(1024) NOT NULL,
  [Bio]NVARCHAR(2000) NOT NULL,
  [Url]nvarchar(450) NULL,
  [Email]NVARCHAR(160) NOT NULL,
  [Type]TINYINT NOT NULL, -- (TINYINT) VAI DE 0 A 255
  CONSTRAINT [PK_Author] PRIMARY KEY ([Id])
);
GO

-- ESTRUTURA DA TABELA CARREIRA
CREATE TABLE [Career]
(
  [Id]uniqueidentifier NOT NULL,
  [Title]NVARCHAR(160) NOT NULL,
  [Summary]NVARCHAR(2000) NOT NULL,
  [Url]NVARCHAR(1024) NOT NULL,
  [DurationInMinutes]INT NOT NULL,
  [Active]BIT NOT NULL, -- BIT(BOLEANO)(TRUE/FASE)
  [Featured]BIT NOT NULL, -- FEATURED SE ESTA EM DESTAQUE NO SITE(TRUE/FASE)
  [Tags]NVARCHAR(160) NOT NULL,
  CONSTRAINT [PK_Career] PRIMARY KEY([Id])
);
GO

-- ESTRUTURA DA TABELA CATEGORIA
CREATE TABLE [Category]
(
  [Id]uniqueidentifier NOT NULL,
  [Title]NVARCHAR(160) NOT NULL,
  [Url]NVARCHAR(1024) NOT NULL,
  [Summary]NVARCHAR(2000) NOT NULL,
  [Order]int NOT NULL,
  [Description]TEXT NOT NULL, -- IRA ARMAZENA APENAS TEXTO
  [Featured] BIT NOT NULL,
  CONSTRAINT [PK_Category] PRIMARY KEY ([Id])
);
GO

-- ESTRUTURA DA TABELA CURSO
CREATE TABLE [Course]
(
  [Id]uniqueidentifier NOT NULL,
  [Tag]NVARCHAR(20) NOT NULL, -- TAG DO CURSO
  [Title]NVARCHAR(160) NOT NULL, -- TITULO DO CURSO
  [Summary]NVARCHAR(2000) NOT NULL, -- DESCRIÇÃO DO CURSO
  [Url]NVARCHAR (1024)NOT NULL, -- URL AMIGÁVEL DO CURSO
  [Level]TINYINT NOT NULL, -- UM ENUMERADOR NO CSHARP NÍVEL(INICIANTE, INTERMEDIÁRIO, AVANÇADO)
  [DurationInMinutes]INT NOT NULL, -- DURAÇÃO DO CURSO EM MINUTOS
  [CreateDate]DATETIME NOT NULL, -- DATA DE CRIAÇÃO DO DATETIME
  [LastUpdateDate]DATETIME NOT NULL, -- DATA DA ULTIMA ATUALIZAÇÃO DESSE CURSO
  [Active]BIT NOT NULL, -- FLAG SE O CURSO TA ATIVO
  [Free]BIT NOT NULL, -- FLAG SE ELE É FREE(SE ELE TA GRATUITO OU PAGO)
  [Featured]BIT NOT NULL, -- SE O CURSO ESTA EM DESTAQUE
  [AuthorId]uniqueidentifier NOT NULL, -- REFERENCIAS AO AUTOR DO CURSO
  [CategoryId]uniqueidentifier NOT NULL, -- CATEGORIA DESSE CURSO
  [Tags]NVARCHAR (160) NOT NULL,
  CONSTRAINT [PK_Course] PRIMARY KEY ([Id]),
  CONSTRAINT [FK_Course_Author_AuthorId] FOREIGN KEY ([AuthorId]) REFERENCES [Author]([Id]) ON DELETE NO ACTION,
  CONSTRAINT [FK_Course_Category_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [Category] ([Id]) ON DELETE NO ACTION,
);
GO

-- ESTRUTURA DA TABELA DE CARRERA ITEM
CREATE TABLE [CareerItem]
(
  [CareerId]uniqueidentifier NOT NULL,
  [CourseId]uniqueidentifier NOT NULL,
  [Title]NVARCHAR (160) NOT NULL,
  [Description]TEXT NOT NULL,
  [Order]TINYINT NOT NULL,
  CONSTRAINT [PK_CareerItem] PRIMARY KEY ([CourseId], [CareerId]),
  CONSTRAINT [FK_CareerItem_Career_CareerId] FOREIGN KEY ([CareerId]) REFERENCES [Career]([Id]) ON DELETE NO ACTION,
  CONSTRAINT [FK_CareerItem_Course-CourseId] FOREIGN KEY ([CourseId]) REFERENCES [Course]([Id]) ON DELETE NO ACTION,
);
GO

-- ESTRUTURA DA TABELA DE ESTUDANTE CURSO
CREATE TABLE [StudentCourse]
(
  [CourseId]uniqueidentifier NOT NULL,
  [StudentId]uniqueidentifier NOT NULL, 
  [Progress]TINYINT NOT NULL,
  [Favorite]BIT NOT NULL,
  [StartDate]DATETIME NOT NULL,
  [LastUpdateDate] DATETIME NULL,
  CONSTRAINT [PK_StudentCourse] PRIMARY KEY ([CourseId], [StudentId]),
  CONSTRAINT [FK_StudentCourse_Course_CourseId] FOREIGN KEY ([CourseId]) REFERENCES [Course]([Id]),
  CONSTRAINT [FP_StudentCourse_Student_StudentId] FOREIGN KEY ([StudentId]) REFERENCES [Student]([Id]),
);
GO