--UPDATE
select * from[Categoria]
-- (COMMIT) CONFIRMAR 
-- (ROLLBACK) DESFAZER

BEGIN TRANSACTION -- INICIEI UMA TRANSAÇÃO
    UPDATE -- FIZ UM UPDATE NA TABELA (CATEGORIA)
        [Categoria]
    SET -- ATRIBUI O (NOME)PARA 'BACKEND'
        [Nome] = 'Backend'
    WHERE -- A ONDE O (ID) SEJA 1
        [Id] = 1
COMMIT
-- ROLLBACK -- SEMPRE USAR O (ROLLBACK) NO FINAL PRA TESTAR SE DEU CERTO, E DPS ELE DA UM ROLLBACK
