-- ELE É IMPORTANTE PARA PODE JUNTAR MAIS TABELA, COMO POR EX: A DE CURSO COM A TABELA DE CATEGORIA
-- ALIAS (AS)
SELECT TOP 100
    COUNT([Id]) AS [Total] --EXEMPLO 1 (FICA MAIS ORGANIZADO COM ESSE MÉTODO)
    --[Id] AS [Codigo], --EXEMPLO 2
FROM
    [Curso]


--EXEMPLO 3 (SELECIONA UM USER)
SELECT * FROM [User]

--EXEMPLO 4 (INSERI UM ITEM)
INSERT INTO [Role] VALUES ('Autor', 'author')