// OPERARADORES RELACIONAIS
/* 
>
:=
<
<=
== (QUANDO EU UTILIZO == É UMA OPERAÇÃO DE COMPARACAO EU TO COMPARANDO O VALOR DE UMA VARIAVEL AO DE OUTRA VARIAVEL)
= (QUANDO NOIS UTILIZA APENAS UM = EM JAVASCRIPT E UMA OPERAÇÃO DE ATRIBUIÇÃO TO FALANDO QUE UMA VARIAVEL RECEBE UM VALOR)
!=
*/
let num1 = 10
let num2 = 5
let num3 = 10

console.log(num1 != num3)

